[font]
size = 14

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.8

[window.padding]
x = 0
y = 0

[scrolling]
history = 100000
multiplier = 1

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]

[colors]
[colors.primary]
background = "0x282828"
foreground = "0xd4be98"

[colors.normal]
black = "0x3c3836"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

[colors.bright]
black = "0x3c3836"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"
